version: '3.8'

services:
  #mongodb:
  #  image: mongo:latest
   # container_name: mongodb
  ##  restart: always
  #  environment:
  #    MONGO_INITDB_ROOT_USERNAME: root
  #    MONGO_INITDB_ROOT_PASSWORD: example
 #   ports:
 #     - "27017:27017"
 #   volumes:
  #    - mongo_data:/data/db

  core:
    build: ./core
    container_name: core-app
    restart: always
    ports:
      - "7777:7777"
    #depends_on:
     # - mongodb
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://root:example@mongodb:27017/main?authSource=admin
      SERVER_PORT: 7777

  frontend:
    build: ./frontend
    container_name: frontend-app
    restart: always
    ports:
      - "4000:4000"
    environment:
      #VITE_API_URL: "https://blinkback.of44.fun"
      VITE_API_URL: "https://blinkback.ru.tuna.am"
    command: npm run dev -- --host 0.0.0.0 --port 4000

volumes:
  mongo_data:
