spring:
  application:
    name: core
  data:
    mongodb:
      uri: mongodb://localhost:27017/main
  cloud:
    openfeign:
      okhttp:
        enabled: true
      httpclient:
        enabled: false

server:
  port: 7777
  error:
    include-stacktrace: always

telegram:
  bot:
    token: 8599381368:AAHGZ83MVpuZLQDfXtoS7Ra3a3qlwE8-rsE

logging:
  level:
    com.blinkgift.core.security: DEBUG
    org.springframework.web: DEBUG
    com.blinkgift.core: DEBUG
    org.apache.coyote: DEBUG
    org.apache.tomcat: DEBUG

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 10000
        loggerLevel: basic